### ISSUE TITLE
trying to build but failing on ubuntu

### ISSUE THREAD

**Issue by francispoulin** [adamcandy/Shingle#3]
Thanks for putting this together.  I am very keen to try it out but I am still at the first phase of trying to installing it.

I believe I have installed the required libraries.  One difference is I installed python-gdal on ubuntu and I have to import it using "import gdal" instead of "import GDAL" and I believe you have in the code.  Not sure if that is a problem or not.

I downloaded your code and tried to build it but didn't get very far.  Do you have any advice as to what I should do?  

```

$ python setup.py build
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'library_dirs'
  warnings.warn(msg)
running build
running build_py
running egg_info
writing shingle.egg-info/PKG-INFO
writing top-level names to shingle.egg-info/top_level.txt
writing dependency_links to shingle.egg-info/dependency_links.txt
writing entry points to shingle.egg-info/entry_points.txt
reading manifest file 'shingle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'MANIFEST'
warning: no files found matching '*.py' under directory 'shingle/'
warning: no files found matching '*.so' under directory 'shingle/'
warning: no files found matching '*.h' under directory 'spud/include/'
no previously-included directories found matching 'dataset'
warning: no previously-included files matching '*' found under directory 'dataset/'
writing manifest file 'shingle.egg-info/SOURCES.txt'
running build_ext
building 'libspud' extension
gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-lMBuS3/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/fpoulin/software/Shingle/spud/include -I/home/fpoulin/software/Shingle/spud/include -I/usr/include/python2.7 -c spud/python/libspud.c -o build/temp.linux-x86_64-2.7/spud/python/libspud.o
In file included from spud/python/libspud.c:3:0:
/home/fpoulin/software/Shingle/spud/include/spud.h:38:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   void spud_clear_options();
   ^~~~
/home/fpoulin/software/Shingle/spud/include/spud.h:39:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   void* spud_get_manager();
   ^~~~
/home/fpoulin/software/Shingle/spud/include/spud.h:70:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   void spud_print_options();
   ^~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-lMBuS3/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-lMBuS3/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/spud/python/libspud.o -L/home/fpoulin/software/Shingle/spud -lspud -o build/lib.linux-x86_64-2.7/libspud.so -flat_namespace -lstdc++
x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-flat_namespace’; did you mean ‘-Wnamespaces’?
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by adamcandy** [comment]
This issue was moved to shingleproject/Shingle#2

**Comment by adamcandy** [comment]
@francispoulin, thank you for the reporting the issue.  I have moved it to the main project repository [shingleproject/Shingle](https://github.com/shingleproject/Shingle) where it appears as shingleproject/Shingle#2.  My suggestions are copied below.  It would be great to hear at shingleproject/Shingle#2 if this helps and you are able to now successfully build and test the library.

--

Thank you @francispoulin for your interest in the Shingle library.  The dependencies of the library in version 2 have grown to include *libspud* to formally manage the diverse range of option types -- and the building of this library appears to be failing here.

## Libspud dependency build suggestions

To help solve this problem for you and others and generally make the setuptools build more agnostic to the underlying system the build process has been significantly simplified.  All dependencies provided with the source are now build as extensions within *setup.py* (extensions with C++ code existed before, but this now eliminates the *-lspud* linking, where *-flat_namespace* / *-Wnamespaces* were used).  The *configure -- make* build route still exists, but this Python route should make it easier.

On an updated source (to release [v2.0.2](https://github.com/shingleproject/Shingle/releases/tag/v2.0.2)), you should be able to simply call:



> make

to build the library. This runs `python setup.py build_ext`, as will be called with your `python setup.py build` above.  It also uses `--inplace` to build *libspud.so* directly in the root source folder. You can also use your `python setup.py build` instead if you prefer to build these C++ extensions and collect the library together in a separate `build` folder -- and subsequently install system-wide, if needed.

To run through the unit tests and suite of verification test cases, assessed to expected metrics, follow this with

> make unittest

and

> make test

I recommend the above, but alternatively here are some other suggestions:
* The Spud library code is hosted at: https://launchpad.net/spud, so you could install the library from this code, or its linked Ubuntu packages.
* Use the configure and Makefile mechanisms in the Shingle source code to build the *libspud.so* dynamic library that is the required (or further, enter the spud folder and build separately first)
* Use the pre-prepared PyPI packages, e.g.:

> pip install shingle

Note there is also a PyPI package for the Diamond GUI ([spud-diamond](https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=spud-diamond)), used to examine BRML descriptions.  The PyPI dxdiff package ([dxdiff](https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=dxdiff)) is needed with this.

## General dependency support

To make sure the library builds successfully on a wide range of underlying systems, the above is tested on Travis (follow the link in this badge: [![Build Status](https://travis-ci.org/shingleproject/Shingle.svg?branch=master)](http://travis-ci.org/shingleproject/Shingle)).  This is tested on Ubuntu LTS versions Precise 12.04, Trusty 14.04 and Xenial 16.04, both through Docker container builds and in Travis distributions.

If you find any other issues with dependencies not being found, please refer to these configuration files for lists of apt (and pip) packages -- or use the Docker files themselves directly, which eliminates any potential local configuration issues.  The configuration files are in the root source tree:
* .travis.yml -- configuration for 7 different builds over the 3 Ubuntu LTS systems
* Dockerfile -- Build and testing in Ubuntu Trusty 14.04
* Dockerfile_precise -- Build and testing in Ubuntu Precise 12.04
* Dockerfile_xenial -- Build and testing in Ubuntu Xenial 16.04

Note the first has configurations for environments build up using apt packages and also instead using pip. So following this, you could install dependencies using `pip install` through `setuptools`/`distutils` instead of Ubuntu apt packages.  I would recommend using apt packages first if possible.

## GDAL dependency

Using the Ubuntu `python-gdal` on this release branch to bring in GDAL is fine and should not raise any problems.

All 7 Travis builds are now green  [![Build Status](https://travis-ci.org/shingleproject/Shingle.svg?branch=master)](http://travis-ci.org/shingleproject/Shingle)), which mean the Shingle library builds, unit tests pass and the longer verification tests are successful, following the suring up of the Python setuptools build process.  I will update the manual to reflect the above, and please let me know if this helps fix the issue you have had, or if you experience any other issues.  I would be very interested to hear how you are using the library and welcome input / am happy to help further.
